services:
  secureapita:
    container_name: secureapitacontainer
    build: .
    image: secureapita:v1
    ports:
      -80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
  driver: bridge
