apiVersion: v1
kind: Service
metadata:
    name: bollywoodapi-service
    labels:
        name: bollywoodapi
spec:
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: bollywoodapi
    type: LoadBalancer